version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  labels:
  - "CI/CD"
  commit-message:
    prefix: ci
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: '20:00'
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: '20:00'
  open-pull-requests-limit: 10
